## Preprocessing

In [33]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [34]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN', 'NAME'], inplace=True)

In [35]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

Target variable is IS_SUCCESSFUL
The rest are feature variables.

In [36]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [37]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [38]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# Choose a cutoff value (e.g., 1000)
cutoff_value = 500

# Create a list of application types to be replaced
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [39]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [40]:
# You may find it helpful to look at CLASSIFICATION value counts >1
infreq_classification_counts = classification_counts[classification_counts>1]
infreq_classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [41]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1500

# Create a list of application types to be replaced
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [42]:
# Convert categorical data to numeric with `pd.get_dummies`
# Convert categorical data to numeric using one-hot encoding
application_df_encoded = pd.get_dummies(application_df)

# Display the encoded DataFrame
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [43]:
# Split our preprocessed data into our features and target arrays
y = application_df_encoded.IS_SUCCESSFUL.values
X = application_df_encoded.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [44]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [45]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

# Define the number of input features
input_features = len(application_df_encoded.columns) - 1  # Exclude the target variable column

# Initialize the Sequential model
nn = tf.keras.models.Sequential()

# Add the first hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=input_features))

# Add the second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Add the third hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Add the output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

c:\Users\kjyon\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 80)             │         3,520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │           992 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,975 (27.25 KB)

 Trainable params: 6,975 (27.25 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 710us/step - accuracy: 0.6971 - loss: 0.5940
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7334 - loss: 0.5521
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - accuracy: 0.7295 - loss: 0.5510
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 726us/step - accuracy: 0.7356 - loss: 0.5480
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.7310 - loss: 0.5476
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.7353 - loss: 0.5467
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - accuracy: 0.7379 - loss: 0.5453
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.7336 - loss: 0.5484
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 723us/step - accuracy: 0.7361 - loss: 0.5470
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.7369 - loss: 0.5438
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 733us/step - accuracy: 0.7385 - loss: 0.5410
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 722us/step - accuracy: 0.7363 - loss: 0.5440
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 729us/step - accuracy: 0.7408 - loss: 0.5402
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7393 - loss: 0.5443
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7334 - loss: 0.5436
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 726us/step - accuracy: 0.7382 - loss: 0.5433
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.7425 - loss: 0.5374
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 734us/step - accuracy: 0.7342 - loss: 0.5441
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.7399 - loss: 0.5434
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7417 - loss: 0.5380
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 734us/step - accuracy: 0.7374 - loss: 0.5423
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.7408 - loss: 0.5369
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 739us/step - accuracy: 0.7391 - loss: 0.5375
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 744us/step - accuracy: 0.7339 - loss: 0.5426
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - accuracy: 0.7400 - loss: 0.5406
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.7365 - loss: 0.5377
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 755us/step - accuracy: 0.7359 - loss: 0.5396
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 747us/step - accuracy: 0.7377 - loss: 0.5425
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 775us/step - accuracy: 0.7382 - loss: 0.5381
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.7443 - loss: 0.5338
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 732us/step - accuracy: 0.7392 - loss: 0.5400
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7363 - loss: 0.5427
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 739us/step - accuracy: 0.7400 - loss: 0.5397
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.7437 - loss: 0.5356
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 733us/step - accuracy: 0.7398 - loss: 0.5398
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 734us/step - accuracy: 0.7411 - loss: 0.5362
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 730us/step - accuracy: 0.7388 - loss: 0.5403
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.7436 - loss: 0.5348
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7437 - loss: 0.5363
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - accuracy: 0.7416 - loss: 0.5341
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 820us/step - accuracy: 0.7386 - loss: 0.5387
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7391 - loss: 0.5397
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.7417 - loss: 0.5343
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.7399 - loss: 0.5393
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.7459 - loss: 0.5331
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 749us/step - accuracy: 0.7393 - loss: 0.5402
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 756us/step - accuracy: 0.7434 - loss: 0.5352
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.7359 - loss: 0.5400
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - accuracy: 0.7371 - loss: 0.5407
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7464 - loss: 0.5314
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 838us/step - accuracy: 0.7449 - loss: 0.5334
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.7376 - loss: 0.5382
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - accuracy: 0.7476 - loss: 0.5294
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 742us/step - accuracy: 0.7415 - loss: 0.5344
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.7367 - loss: 0.5397
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - accuracy: 0.7346 - loss: 0.5414
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.7382 - loss: 0.5360
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - accuracy: 0.7412 - loss: 0.5356
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7345 - loss: 0.5375
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 745us/step - accuracy: 0.7433 - loss: 0.5332
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - accuracy: 0.7375 - loss: 0.5379
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.7434 - loss: 0.5359
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7415 - loss: 0.5357
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7361 - loss: 0.5365
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - accuracy: 0.7438 - loss: 0.5352
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - accuracy: 0.7374 - loss: 0.5398
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 757us/step - accuracy: 0.7380 - loss: 0.5365
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.7411 - loss: 0.5385
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.7396 - loss: 0.5355
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 747us/step - accuracy: 0.7407 - loss: 0.5349
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 755us/step - accuracy: 0.7436 - loss: 0.5349
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 829us/step - accuracy: 0.7437 - loss: 0.5328
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 755us/step - accuracy: 0.7462 - loss: 0.5312
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 753us/step - accuracy: 0.7446 - loss: 0.5318
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.7457 - loss: 0.5281
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.7453 - loss: 0.5271
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.7406 - loss: 0.5340
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 779us/step - accuracy: 0.7405 - loss: 0.5327
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.7386 - loss: 0.5369
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7439 - loss: 0.5314
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.7387 - loss: 0.5326
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 773us/step - accuracy: 0.7422 - loss: 0.5315
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 878us/step - accuracy: 0.7399 - loss: 0.5368
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 910us/step - accuracy: 0.7414 - loss: 0.5334
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - accuracy: 0.7418 - loss: 0.5320
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 756us/step - accuracy: 0.7353 - loss: 0.5425
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.7397 - loss: 0.5348
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.7484 - loss: 0.5290
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.7478 - loss: 0.5309
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.7435 - loss: 0.5338
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.7424 - loss: 0.5327
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.7436 - loss: 0.5326
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 753us/step - accuracy: 0.7428 - loss: 0.5330
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.7432 - loss: 0.5310
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - accuracy: 0.7391 - loss: 0.5374
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.7425 - loss: 0.5299
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 766us/step - accuracy: 0.7471 - loss: 0.5247
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7407 - loss: 0.5327
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 829us/step - accuracy: 0.7408 - loss: 0.5352
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 761us/step - accuracy: 0.7443 - loss: 0.5326

In [47]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 962us/step - accuracy: 0.7255 - loss: 0.5626
Loss: 0.5626048445701599, Accuracy: 0.7254810333251953

In [48]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.keras")

ImportError: h5py must be installed in order to save a model.